// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: domunity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_domunity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	User          *User                  `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_domunity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_domunity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_domunity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_domunity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_domunity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_domunity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{6}
}

func (x *ForgotPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_domunity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{7}
}

func (x *ForgotPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForgotPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_domunity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_domunity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{9}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UserProfile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	User            *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Building        *Building              `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"`
	Apartment       *Apartment             `protobuf:"bytes,3,opt,name=apartment,proto3" json:"apartment,omitempty"`
	AccountManager  string                 `protobuf:"bytes,4,opt,name=account_manager,json=accountManager,proto3" json:"account_manager,omitempty"`
	Balance         float64                `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	ClientNumber    string                 `protobuf:"bytes,6,opt,name=client_number,json=clientNumber,proto3" json:"client_number,omitempty"`
	ContractEndDate string                 `protobuf:"bytes,7,opt,name=contract_end_date,json=contractEndDate,proto3" json:"contract_end_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_domunity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{10}
}

func (x *UserProfile) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserProfile) GetBuilding() *Building {
	if x != nil {
		return x.Building
	}
	return nil
}

func (x *UserProfile) GetApartment() *Apartment {
	if x != nil {
		return x.Apartment
	}
	return nil
}

func (x *UserProfile) GetAccountManager() string {
	if x != nil {
		return x.AccountManager
	}
	return ""
}

func (x *UserProfile) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserProfile) GetClientNumber() string {
	if x != nil {
		return x.ClientNumber
	}
	return ""
}

func (x *UserProfile) GetContractEndDate() string {
	if x != nil {
		return x.ContractEndDate
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_domunity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_domunity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBuildingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildingId    string                 `protobuf:"bytes,1,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildingRequest) Reset() {
	*x = GetBuildingRequest{}
	mi := &file_domunity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildingRequest) ProtoMessage() {}

func (x *GetBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildingRequest.ProtoReflect.Descriptor instead.
func (*GetBuildingRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{13}
}

func (x *GetBuildingRequest) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

type Building struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address         string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Entrance        string                 `protobuf:"bytes,3,opt,name=entrance,proto3" json:"entrance,omitempty"`
	TotalApartments int32                  `protobuf:"varint,4,opt,name=total_apartments,json=totalApartments,proto3" json:"total_apartments,omitempty"`
	TotalResidents  int32                  `protobuf:"varint,5,opt,name=total_residents,json=totalResidents,proto3" json:"total_residents,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Building) Reset() {
	*x = Building{}
	mi := &file_domunity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Building) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Building) ProtoMessage() {}

func (x *Building) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Building.ProtoReflect.Descriptor instead.
func (*Building) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{14}
}

func (x *Building) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Building) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Building) GetEntrance() string {
	if x != nil {
		return x.Entrance
	}
	return ""
}

func (x *Building) GetTotalApartments() int32 {
	if x != nil {
		return x.TotalApartments
	}
	return 0
}

func (x *Building) GetTotalResidents() int32 {
	if x != nil {
		return x.TotalResidents
	}
	return 0
}

type Apartment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildingId    string                 `protobuf:"bytes,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	Number        int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Floor         int32                  `protobuf:"varint,4,opt,name=floor,proto3" json:"floor,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Residents     int32                  `protobuf:"varint,6,opt,name=residents,proto3" json:"residents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Apartment) Reset() {
	*x = Apartment{}
	mi := &file_domunity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Apartment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apartment) ProtoMessage() {}

func (x *Apartment) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apartment.ProtoReflect.Descriptor instead.
func (*Apartment) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{15}
}

func (x *Apartment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Apartment) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

func (x *Apartment) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Apartment) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *Apartment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Apartment) GetResidents() int32 {
	if x != nil {
		return x.Residents
	}
	return 0
}

type ListApartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildingId    string                 `protobuf:"bytes,1,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApartmentsRequest) Reset() {
	*x = ListApartmentsRequest{}
	mi := &file_domunity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApartmentsRequest) ProtoMessage() {}

func (x *ListApartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApartmentsRequest.ProtoReflect.Descriptor instead.
func (*ListApartmentsRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{16}
}

func (x *ListApartmentsRequest) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

type ListApartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apartments    []*Apartment           `protobuf:"bytes,1,rep,name=apartments,proto3" json:"apartments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApartmentsResponse) Reset() {
	*x = ListApartmentsResponse{}
	mi := &file_domunity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApartmentsResponse) ProtoMessage() {}

func (x *ListApartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApartmentsResponse.ProtoReflect.Descriptor instead.
func (*ListApartmentsResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{17}
}

func (x *ListApartmentsResponse) GetApartments() []*Apartment {
	if x != nil {
		return x.Apartments
	}
	return nil
}

type GetFinancialReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BuildingId    string                 `protobuf:"bytes,2,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFinancialReportRequest) Reset() {
	*x = GetFinancialReportRequest{}
	mi := &file_domunity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFinancialReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinancialReportRequest) ProtoMessage() {}

func (x *GetFinancialReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinancialReportRequest.ProtoReflect.Descriptor instead.
func (*GetFinancialReportRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{18}
}

func (x *GetFinancialReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFinancialReportRequest) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

type FinancialReportEntry struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ApartmentNumber       int32                  `protobuf:"varint,1,opt,name=apartment_number,json=apartmentNumber,proto3" json:"apartment_number,omitempty"`
	Type                  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Floor                 int32                  `protobuf:"varint,3,opt,name=floor,proto3" json:"floor,omitempty"`
	ClientName            string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	Residents             int32                  `protobuf:"varint,5,opt,name=residents,proto3" json:"residents,omitempty"`
	ElevatorGtp           float64                `protobuf:"fixed64,6,opt,name=elevator_gtp,json=elevatorGtp,proto3" json:"elevator_gtp,omitempty"`
	ElevatorElectricity   float64                `protobuf:"fixed64,7,opt,name=elevator_electricity,json=elevatorElectricity,proto3" json:"elevator_electricity,omitempty"`
	CommonAreaElectricity float64                `protobuf:"fixed64,8,opt,name=common_area_electricity,json=commonAreaElectricity,proto3" json:"common_area_electricity,omitempty"`
	ElevatorMaintenance   float64                `protobuf:"fixed64,9,opt,name=elevator_maintenance,json=elevatorMaintenance,proto3" json:"elevator_maintenance,omitempty"`
	ManagementFee         float64                `protobuf:"fixed64,10,opt,name=management_fee,json=managementFee,proto3" json:"management_fee,omitempty"`
	RepairFund            float64                `protobuf:"fixed64,11,opt,name=repair_fund,json=repairFund,proto3" json:"repair_fund,omitempty"`
	TotalDue              float64                `protobuf:"fixed64,12,opt,name=total_due,json=totalDue,proto3" json:"total_due,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FinancialReportEntry) Reset() {
	*x = FinancialReportEntry{}
	mi := &file_domunity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialReportEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialReportEntry) ProtoMessage() {}

func (x *FinancialReportEntry) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialReportEntry.ProtoReflect.Descriptor instead.
func (*FinancialReportEntry) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{19}
}

func (x *FinancialReportEntry) GetApartmentNumber() int32 {
	if x != nil {
		return x.ApartmentNumber
	}
	return 0
}

func (x *FinancialReportEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FinancialReportEntry) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *FinancialReportEntry) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *FinancialReportEntry) GetResidents() int32 {
	if x != nil {
		return x.Residents
	}
	return 0
}

func (x *FinancialReportEntry) GetElevatorGtp() float64 {
	if x != nil {
		return x.ElevatorGtp
	}
	return 0
}

func (x *FinancialReportEntry) GetElevatorElectricity() float64 {
	if x != nil {
		return x.ElevatorElectricity
	}
	return 0
}

func (x *FinancialReportEntry) GetCommonAreaElectricity() float64 {
	if x != nil {
		return x.CommonAreaElectricity
	}
	return 0
}

func (x *FinancialReportEntry) GetElevatorMaintenance() float64 {
	if x != nil {
		return x.ElevatorMaintenance
	}
	return 0
}

func (x *FinancialReportEntry) GetManagementFee() float64 {
	if x != nil {
		return x.ManagementFee
	}
	return 0
}

func (x *FinancialReportEntry) GetRepairFund() float64 {
	if x != nil {
		return x.RepairFund
	}
	return 0
}

func (x *FinancialReportEntry) GetTotalDue() float64 {
	if x != nil {
		return x.TotalDue
	}
	return 0
}

type FinancialReport struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Entries       []*FinancialReportEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalBalance  float64                 `protobuf:"fixed64,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinancialReport) Reset() {
	*x = FinancialReport{}
	mi := &file_domunity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialReport) ProtoMessage() {}

func (x *FinancialReport) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialReport.ProtoReflect.Descriptor instead.
func (*FinancialReport) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{20}
}

func (x *FinancialReport) GetEntries() []*FinancialReportEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FinancialReport) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

type GetPaymentHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentHistoryRequest) Reset() {
	*x = GetPaymentHistoryRequest{}
	mi := &file_domunity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentHistoryRequest) ProtoMessage() {}

func (x *GetPaymentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{21}
}

func (x *GetPaymentHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_domunity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{22}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PaymentHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentHistory) Reset() {
	*x = PaymentHistory{}
	mi := &file_domunity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentHistory) ProtoMessage() {}

func (x *PaymentHistory) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentHistory.ProtoReflect.Descriptor instead.
func (*PaymentHistory) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{23}
}

func (x *PaymentHistory) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildingId    string                 `protobuf:"bytes,1,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_domunity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{24}
}

func (x *ListEventsRequest) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	BuildingId    string                 `protobuf:"bytes,5,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_domunity_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{25}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_domunity_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{26}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildingId    string                 `protobuf:"bytes,1,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_domunity_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{27}
}

func (x *CreateEventRequest) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

func (x *CreateEventRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_domunity_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{28}
}

func (x *CreateEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ContactFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactFormRequest) Reset() {
	*x = ContactFormRequest{}
	mi := &file_domunity_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFormRequest) ProtoMessage() {}

func (x *ContactFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFormRequest.ProtoReflect.Descriptor instead.
func (*ContactFormRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{29}
}

func (x *ContactFormRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactFormRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ContactFormRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactFormRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContactFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactFormResponse) Reset() {
	*x = ContactFormResponse{}
	mi := &file_domunity_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFormResponse) ProtoMessage() {}

func (x *ContactFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFormResponse.ProtoReflect.Descriptor instead.
func (*ContactFormResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{30}
}

func (x *ContactFormResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ContactFormResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OfferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Phone          string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	City           string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	NumProperties  int32                  `protobuf:"varint,4,opt,name=num_properties,json=numProperties,proto3" json:"num_properties,omitempty"`
	Address        string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	AdditionalInfo string                 `protobuf:"bytes,6,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OfferRequest) Reset() {
	*x = OfferRequest{}
	mi := &file_domunity_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferRequest) ProtoMessage() {}

func (x *OfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferRequest.ProtoReflect.Descriptor instead.
func (*OfferRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{31}
}

func (x *OfferRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OfferRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OfferRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OfferRequest) GetNumProperties() int32 {
	if x != nil {
		return x.NumProperties
	}
	return 0
}

func (x *OfferRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OfferRequest) GetAdditionalInfo() string {
	if x != nil {
		return x.AdditionalInfo
	}
	return ""
}

type OfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferResponse) Reset() {
	*x = OfferResponse{}
	mi := &file_domunity_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferResponse) ProtoMessage() {}

func (x *OfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferResponse.ProtoReflect.Descriptor instead.
func (*OfferResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{32}
}

func (x *OfferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OfferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PresentationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Date           string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	BuildingType   string                 `protobuf:"bytes,2,opt,name=building_type,json=buildingType,proto3" json:"building_type,omitempty"`
	Phone          string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address        string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	AdditionalInfo string                 `protobuf:"bytes,6,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PresentationRequest) Reset() {
	*x = PresentationRequest{}
	mi := &file_domunity_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentationRequest) ProtoMessage() {}

func (x *PresentationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentationRequest.ProtoReflect.Descriptor instead.
func (*PresentationRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{33}
}

func (x *PresentationRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PresentationRequest) GetBuildingType() string {
	if x != nil {
		return x.BuildingType
	}
	return ""
}

func (x *PresentationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PresentationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PresentationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PresentationRequest) GetAdditionalInfo() string {
	if x != nil {
		return x.AdditionalInfo
	}
	return ""
}

type PresentationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresentationResponse) Reset() {
	*x = PresentationResponse{}
	mi := &file_domunity_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentationResponse) ProtoMessage() {}

func (x *PresentationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentationResponse.ProtoReflect.Descriptor instead.
func (*PresentationResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{34}
}

func (x *PresentationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PresentationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_domunity_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{35}
}

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DatabaseStatus string                 `protobuf:"bytes,3,opt,name=database_status,json=databaseStatus,proto3" json:"database_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_domunity_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domunity_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_domunity_proto_rawDescGZIP(), []int{36}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetDatabaseStatus() string {
	if x != nil {
		return x.DatabaseStatus
	}
	return ""
}

var File_domunity_proto protoreflect.FileDescriptor

const file_domunity_proto_rawDesc = "" +
	"\n" +
	"\x0edomunity.proto\x12\bdomunity\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xaf\x01\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\"\n" +
	"\x04user\x18\x05 \x01(\v2\x0e.domunity.UserR\x04user\"v\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"_\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"S\n" +
	"\x14RefreshTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"-\n" +
	"\x15ForgotPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"L\n" +
	"\x16ForgotPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"~\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xa8\x02\n" +
	"\vUserProfile\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.domunity.UserR\x04user\x12.\n" +
	"\bbuilding\x18\x02 \x01(\v2\x12.domunity.BuildingR\bbuilding\x121\n" +
	"\tapartment\x18\x03 \x01(\v2\x13.domunity.ApartmentR\tapartment\x12'\n" +
	"\x0faccount_manager\x18\x04 \x01(\tR\x0eaccountManager\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x01R\abalance\x12#\n" +
	"\rclient_number\x18\x06 \x01(\tR\fclientNumber\x12*\n" +
	"\x11contract_end_date\x18\a \x01(\tR\x0fcontractEndDate\"b\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"K\n" +
	"\x15UpdateProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x12GetBuildingRequest\x12\x1f\n" +
	"\vbuilding_id\x18\x01 \x01(\tR\n" +
	"buildingId\"\xa4\x01\n" +
	"\bBuilding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bentrance\x18\x03 \x01(\tR\bentrance\x12)\n" +
	"\x10total_apartments\x18\x04 \x01(\x05R\x0ftotalApartments\x12'\n" +
	"\x0ftotal_residents\x18\x05 \x01(\x05R\x0etotalResidents\"\x9c\x01\n" +
	"\tApartment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\tR\n" +
	"buildingId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12\x14\n" +
	"\x05floor\x18\x04 \x01(\x05R\x05floor\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1c\n" +
	"\tresidents\x18\x06 \x01(\x05R\tresidents\"8\n" +
	"\x15ListApartmentsRequest\x12\x1f\n" +
	"\vbuilding_id\x18\x01 \x01(\tR\n" +
	"buildingId\"M\n" +
	"\x16ListApartmentsResponse\x123\n" +
	"\n" +
	"apartments\x18\x01 \x03(\v2\x13.domunity.ApartmentR\n" +
	"apartments\"U\n" +
	"\x19GetFinancialReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vbuilding_id\x18\x02 \x01(\tR\n" +
	"buildingId\"\xd0\x03\n" +
	"\x14FinancialReportEntry\x12)\n" +
	"\x10apartment_number\x18\x01 \x01(\x05R\x0fapartmentNumber\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05floor\x18\x03 \x01(\x05R\x05floor\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12\x1c\n" +
	"\tresidents\x18\x05 \x01(\x05R\tresidents\x12!\n" +
	"\felevator_gtp\x18\x06 \x01(\x01R\velevatorGtp\x121\n" +
	"\x14elevator_electricity\x18\a \x01(\x01R\x13elevatorElectricity\x126\n" +
	"\x17common_area_electricity\x18\b \x01(\x01R\x15commonAreaElectricity\x121\n" +
	"\x14elevator_maintenance\x18\t \x01(\x01R\x13elevatorMaintenance\x12%\n" +
	"\x0emanagement_fee\x18\n" +
	" \x01(\x01R\rmanagementFee\x12\x1f\n" +
	"\vrepair_fund\x18\v \x01(\x01R\n" +
	"repairFund\x12\x1b\n" +
	"\ttotal_due\x18\f \x01(\x01R\btotalDue\"p\n" +
	"\x0fFinancialReport\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.domunity.FinancialReportEntryR\aentries\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x01R\ftotalBalance\"3\n" +
	"\x18GetPaymentHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x7f\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"?\n" +
	"\x0ePaymentHistory\x12-\n" +
	"\bpayments\x18\x01 \x03(\v2\x11.domunity.PaymentR\bpayments\"J\n" +
	"\x11ListEventsRequest\x12\x1f\n" +
	"\vbuilding_id\x18\x01 \x01(\tR\n" +
	"buildingId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x84\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vbuilding_id\x18\x05 \x01(\tR\n" +
	"buildingId\"=\n" +
	"\x12ListEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.domunity.EventR\x06events\"\x81\x01\n" +
	"\x12CreateEventRequest\x12\x1f\n" +
	"\vbuilding_id\x18\x01 \x01(\tR\n" +
	"buildingId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"d\n" +
	"\x13CreateEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"n\n" +
	"\x12ContactFormRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"I\n" +
	"\x13ContactFormResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb8\x01\n" +
	"\fOfferRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12%\n" +
	"\x0enum_properties\x18\x04 \x01(\x05R\rnumProperties\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12'\n" +
	"\x0fadditional_info\x18\x06 \x01(\tR\x0eadditionalInfo\"C\n" +
	"\rOfferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbd\x01\n" +
	"\x13PresentationRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12#\n" +
	"\rbuilding_type\x18\x02 \x01(\tR\fbuildingType\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12'\n" +
	"\x0fadditional_info\x18\x06 \x01(\tR\x0eadditionalInfo\"J\n" +
	"\x14PresentationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthCheckRequest\"r\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fdatabase_status\x18\x03 \x01(\tR\x0edatabaseStatus2\xb6\x02\n" +
	"\vAuthService\x12:\n" +
	"\x05Login\x12\x16.domunity.LoginRequest\x1a\x17.domunity.LoginResponse\"\x00\x12C\n" +
	"\bRegister\x12\x19.domunity.RegisterRequest\x1a\x1a.domunity.RegisterResponse\"\x00\x12O\n" +
	"\fRefreshToken\x12\x1d.domunity.RefreshTokenRequest\x1a\x1e.domunity.RefreshTokenResponse\"\x00\x12U\n" +
	"\x0eForgotPassword\x12\x1f.domunity.ForgotPasswordRequest\x1a .domunity.ForgotPasswordResponse\"\x002\xa5\x01\n" +
	"\vUserService\x12B\n" +
	"\n" +
	"GetProfile\x12\x1b.domunity.GetProfileRequest\x1a\x15.domunity.UserProfile\"\x00\x12R\n" +
	"\rUpdateProfile\x12\x1e.domunity.UpdateProfileRequest\x1a\x1f.domunity.UpdateProfileResponse\"\x002\xab\x01\n" +
	"\x0fBuildingService\x12A\n" +
	"\vGetBuilding\x12\x1c.domunity.GetBuildingRequest\x1a\x12.domunity.Building\"\x00\x12U\n" +
	"\x0eListApartments\x12\x1f.domunity.ListApartmentsRequest\x1a .domunity.ListApartmentsResponse\"\x002\xbf\x01\n" +
	"\x10FinancialService\x12V\n" +
	"\x12GetFinancialReport\x12#.domunity.GetFinancialReportRequest\x1a\x19.domunity.FinancialReport\"\x00\x12S\n" +
	"\x11GetPaymentHistory\x12\".domunity.GetPaymentHistoryRequest\x1a\x18.domunity.PaymentHistory\"\x002\xa7\x01\n" +
	"\fEventService\x12I\n" +
	"\n" +
	"ListEvents\x12\x1b.domunity.ListEventsRequest\x1a\x1c.domunity.ListEventsResponse\"\x00\x12L\n" +
	"\vCreateEvent\x12\x1c.domunity.CreateEventRequest\x1a\x1d.domunity.CreateEventResponse\"\x002\xfd\x01\n" +
	"\x0eContactService\x12P\n" +
	"\x0fSendContactForm\x12\x1c.domunity.ContactFormRequest\x1a\x1d.domunity.ContactFormResponse\"\x00\x12A\n" +
	"\fRequestOffer\x12\x16.domunity.OfferRequest\x1a\x17.domunity.OfferResponse\"\x00\x12V\n" +
	"\x13RequestPresentation\x12\x1d.domunity.PresentationRequest\x1a\x1e.domunity.PresentationResponse\"\x002W\n" +
	"\rHealthService\x12F\n" +
	"\x05Check\x12\x1c.domunity.HealthCheckRequest\x1a\x1d.domunity.HealthCheckResponse\"\x00B#Z!github.com/domunity/backend/protob\x06proto3"

var (
	file_domunity_proto_rawDescOnce sync.Once
	file_domunity_proto_rawDescData []byte
)

func file_domunity_proto_rawDescGZIP() []byte {
	file_domunity_proto_rawDescOnce.Do(func() {
		file_domunity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domunity_proto_rawDesc), len(file_domunity_proto_rawDesc)))
	})
	return file_domunity_proto_rawDescData
}

var file_domunity_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_domunity_proto_goTypes = []any{
	(*LoginRequest)(nil),              // 0: domunity.LoginRequest
	(*LoginResponse)(nil),             // 1: domunity.LoginResponse
	(*RegisterRequest)(nil),           // 2: domunity.RegisterRequest
	(*RegisterResponse)(nil),          // 3: domunity.RegisterResponse
	(*RefreshTokenRequest)(nil),       // 4: domunity.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),      // 5: domunity.RefreshTokenResponse
	(*ForgotPasswordRequest)(nil),     // 6: domunity.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil),    // 7: domunity.ForgotPasswordResponse
	(*GetProfileRequest)(nil),         // 8: domunity.GetProfileRequest
	(*User)(nil),                      // 9: domunity.User
	(*UserProfile)(nil),               // 10: domunity.UserProfile
	(*UpdateProfileRequest)(nil),      // 11: domunity.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),     // 12: domunity.UpdateProfileResponse
	(*GetBuildingRequest)(nil),        // 13: domunity.GetBuildingRequest
	(*Building)(nil),                  // 14: domunity.Building
	(*Apartment)(nil),                 // 15: domunity.Apartment
	(*ListApartmentsRequest)(nil),     // 16: domunity.ListApartmentsRequest
	(*ListApartmentsResponse)(nil),    // 17: domunity.ListApartmentsResponse
	(*GetFinancialReportRequest)(nil), // 18: domunity.GetFinancialReportRequest
	(*FinancialReportEntry)(nil),      // 19: domunity.FinancialReportEntry
	(*FinancialReport)(nil),           // 20: domunity.FinancialReport
	(*GetPaymentHistoryRequest)(nil),  // 21: domunity.GetPaymentHistoryRequest
	(*Payment)(nil),                   // 22: domunity.Payment
	(*PaymentHistory)(nil),            // 23: domunity.PaymentHistory
	(*ListEventsRequest)(nil),         // 24: domunity.ListEventsRequest
	(*Event)(nil),                     // 25: domunity.Event
	(*ListEventsResponse)(nil),        // 26: domunity.ListEventsResponse
	(*CreateEventRequest)(nil),        // 27: domunity.CreateEventRequest
	(*CreateEventResponse)(nil),       // 28: domunity.CreateEventResponse
	(*ContactFormRequest)(nil),        // 29: domunity.ContactFormRequest
	(*ContactFormResponse)(nil),       // 30: domunity.ContactFormResponse
	(*OfferRequest)(nil),              // 31: domunity.OfferRequest
	(*OfferResponse)(nil),             // 32: domunity.OfferResponse
	(*PresentationRequest)(nil),       // 33: domunity.PresentationRequest
	(*PresentationResponse)(nil),      // 34: domunity.PresentationResponse
	(*HealthCheckRequest)(nil),        // 35: domunity.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 36: domunity.HealthCheckResponse
}
var file_domunity_proto_depIdxs = []int32{
	9,  // 0: domunity.LoginResponse.user:type_name -> domunity.User
	9,  // 1: domunity.UserProfile.user:type_name -> domunity.User
	14, // 2: domunity.UserProfile.building:type_name -> domunity.Building
	15, // 3: domunity.UserProfile.apartment:type_name -> domunity.Apartment
	15, // 4: domunity.ListApartmentsResponse.apartments:type_name -> domunity.Apartment
	19, // 5: domunity.FinancialReport.entries:type_name -> domunity.FinancialReportEntry
	22, // 6: domunity.PaymentHistory.payments:type_name -> domunity.Payment
	25, // 7: domunity.ListEventsResponse.events:type_name -> domunity.Event
	0,  // 8: domunity.AuthService.Login:input_type -> domunity.LoginRequest
	2,  // 9: domunity.AuthService.Register:input_type -> domunity.RegisterRequest
	4,  // 10: domunity.AuthService.RefreshToken:input_type -> domunity.RefreshTokenRequest
	6,  // 11: domunity.AuthService.ForgotPassword:input_type -> domunity.ForgotPasswordRequest
	8,  // 12: domunity.UserService.GetProfile:input_type -> domunity.GetProfileRequest
	11, // 13: domunity.UserService.UpdateProfile:input_type -> domunity.UpdateProfileRequest
	13, // 14: domunity.BuildingService.GetBuilding:input_type -> domunity.GetBuildingRequest
	16, // 15: domunity.BuildingService.ListApartments:input_type -> domunity.ListApartmentsRequest
	18, // 16: domunity.FinancialService.GetFinancialReport:input_type -> domunity.GetFinancialReportRequest
	21, // 17: domunity.FinancialService.GetPaymentHistory:input_type -> domunity.GetPaymentHistoryRequest
	24, // 18: domunity.EventService.ListEvents:input_type -> domunity.ListEventsRequest
	27, // 19: domunity.EventService.CreateEvent:input_type -> domunity.CreateEventRequest
	29, // 20: domunity.ContactService.SendContactForm:input_type -> domunity.ContactFormRequest
	31, // 21: domunity.ContactService.RequestOffer:input_type -> domunity.OfferRequest
	33, // 22: domunity.ContactService.RequestPresentation:input_type -> domunity.PresentationRequest
	35, // 23: domunity.HealthService.Check:input_type -> domunity.HealthCheckRequest
	1,  // 24: domunity.AuthService.Login:output_type -> domunity.LoginResponse
	3,  // 25: domunity.AuthService.Register:output_type -> domunity.RegisterResponse
	5,  // 26: domunity.AuthService.RefreshToken:output_type -> domunity.RefreshTokenResponse
	7,  // 27: domunity.AuthService.ForgotPassword:output_type -> domunity.ForgotPasswordResponse
	10, // 28: domunity.UserService.GetProfile:output_type -> domunity.UserProfile
	12, // 29: domunity.UserService.UpdateProfile:output_type -> domunity.UpdateProfileResponse
	14, // 30: domunity.BuildingService.GetBuilding:output_type -> domunity.Building
	17, // 31: domunity.BuildingService.ListApartments:output_type -> domunity.ListApartmentsResponse
	20, // 32: domunity.FinancialService.GetFinancialReport:output_type -> domunity.FinancialReport
	23, // 33: domunity.FinancialService.GetPaymentHistory:output_type -> domunity.PaymentHistory
	26, // 34: domunity.EventService.ListEvents:output_type -> domunity.ListEventsResponse
	28, // 35: domunity.EventService.CreateEvent:output_type -> domunity.CreateEventResponse
	30, // 36: domunity.ContactService.SendContactForm:output_type -> domunity.ContactFormResponse
	32, // 37: domunity.ContactService.RequestOffer:output_type -> domunity.OfferResponse
	34, // 38: domunity.ContactService.RequestPresentation:output_type -> domunity.PresentationResponse
	36, // 39: domunity.HealthService.Check:output_type -> domunity.HealthCheckResponse
	24, // [24:40] is the sub-list for method output_type
	8,  // [8:24] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_domunity_proto_init() }
func file_domunity_proto_init() {
	if File_domunity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domunity_proto_rawDesc), len(file_domunity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_domunity_proto_goTypes,
		DependencyIndexes: file_domunity_proto_depIdxs,
		MessageInfos:      file_domunity_proto_msgTypes,
	}.Build()
	File_domunity_proto = out.File
	file_domunity_proto_goTypes = nil
	file_domunity_proto_depIdxs = nil
}
