# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import domunity_pb2 as domunity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in domunity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """==================== Authentication Service ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/domunity.AuthService/Login',
                request_serializer=domunity__pb2.LoginRequest.SerializeToString,
                response_deserializer=domunity__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/domunity.AuthService/Register',
                request_serializer=domunity__pb2.RegisterRequest.SerializeToString,
                response_deserializer=domunity__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/domunity.AuthService/RefreshToken',
                request_serializer=domunity__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=domunity__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.ForgotPassword = channel.unary_unary(
                '/domunity.AuthService/ForgotPassword',
                request_serializer=domunity__pb2.ForgotPasswordRequest.SerializeToString,
                response_deserializer=domunity__pb2.ForgotPasswordResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """==================== Authentication Service ====================
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgotPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=domunity__pb2.LoginRequest.FromString,
                    response_serializer=domunity__pb2.LoginResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=domunity__pb2.RegisterRequest.FromString,
                    response_serializer=domunity__pb2.RegisterResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=domunity__pb2.RefreshTokenRequest.FromString,
                    response_serializer=domunity__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'ForgotPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgotPassword,
                    request_deserializer=domunity__pb2.ForgotPasswordRequest.FromString,
                    response_serializer=domunity__pb2.ForgotPasswordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'domunity.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('domunity.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """==================== Authentication Service ====================
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.AuthService/Login',
            domunity__pb2.LoginRequest.SerializeToString,
            domunity__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.AuthService/Register',
            domunity__pb2.RegisterRequest.SerializeToString,
            domunity__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.AuthService/RefreshToken',
            domunity__pb2.RefreshTokenRequest.SerializeToString,
            domunity__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgotPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.AuthService/ForgotPassword',
            domunity__pb2.ForgotPasswordRequest.SerializeToString,
            domunity__pb2.ForgotPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserServiceStub(object):
    """==================== User Service ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProfile = channel.unary_unary(
                '/domunity.UserService/GetProfile',
                request_serializer=domunity__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=domunity__pb2.UserProfile.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/domunity.UserService/UpdateProfile',
                request_serializer=domunity__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=domunity__pb2.UpdateProfileResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """==================== User Service ====================
    """

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=domunity__pb2.GetProfileRequest.FromString,
                    response_serializer=domunity__pb2.UserProfile.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=domunity__pb2.UpdateProfileRequest.FromString,
                    response_serializer=domunity__pb2.UpdateProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'domunity.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('domunity.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """==================== User Service ====================
    """

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.UserService/GetProfile',
            domunity__pb2.GetProfileRequest.SerializeToString,
            domunity__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.UserService/UpdateProfile',
            domunity__pb2.UpdateProfileRequest.SerializeToString,
            domunity__pb2.UpdateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BuildingServiceStub(object):
    """==================== Building Service ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBuilding = channel.unary_unary(
                '/domunity.BuildingService/GetBuilding',
                request_serializer=domunity__pb2.GetBuildingRequest.SerializeToString,
                response_deserializer=domunity__pb2.Building.FromString,
                _registered_method=True)
        self.ListApartments = channel.unary_unary(
                '/domunity.BuildingService/ListApartments',
                request_serializer=domunity__pb2.ListApartmentsRequest.SerializeToString,
                response_deserializer=domunity__pb2.ListApartmentsResponse.FromString,
                _registered_method=True)


class BuildingServiceServicer(object):
    """==================== Building Service ====================
    """

    def GetBuilding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApartments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuildingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBuilding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuilding,
                    request_deserializer=domunity__pb2.GetBuildingRequest.FromString,
                    response_serializer=domunity__pb2.Building.SerializeToString,
            ),
            'ListApartments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApartments,
                    request_deserializer=domunity__pb2.ListApartmentsRequest.FromString,
                    response_serializer=domunity__pb2.ListApartmentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'domunity.BuildingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('domunity.BuildingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BuildingService(object):
    """==================== Building Service ====================
    """

    @staticmethod
    def GetBuilding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.BuildingService/GetBuilding',
            domunity__pb2.GetBuildingRequest.SerializeToString,
            domunity__pb2.Building.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApartments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.BuildingService/ListApartments',
            domunity__pb2.ListApartmentsRequest.SerializeToString,
            domunity__pb2.ListApartmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FinancialServiceStub(object):
    """==================== Financial Service ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFinancialReport = channel.unary_unary(
                '/domunity.FinancialService/GetFinancialReport',
                request_serializer=domunity__pb2.GetFinancialReportRequest.SerializeToString,
                response_deserializer=domunity__pb2.FinancialReport.FromString,
                _registered_method=True)
        self.GetPaymentHistory = channel.unary_unary(
                '/domunity.FinancialService/GetPaymentHistory',
                request_serializer=domunity__pb2.GetPaymentHistoryRequest.SerializeToString,
                response_deserializer=domunity__pb2.PaymentHistory.FromString,
                _registered_method=True)


class FinancialServiceServicer(object):
    """==================== Financial Service ====================
    """

    def GetFinancialReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinancialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFinancialReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFinancialReport,
                    request_deserializer=domunity__pb2.GetFinancialReportRequest.FromString,
                    response_serializer=domunity__pb2.FinancialReport.SerializeToString,
            ),
            'GetPaymentHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentHistory,
                    request_deserializer=domunity__pb2.GetPaymentHistoryRequest.FromString,
                    response_serializer=domunity__pb2.PaymentHistory.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'domunity.FinancialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('domunity.FinancialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinancialService(object):
    """==================== Financial Service ====================
    """

    @staticmethod
    def GetFinancialReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.FinancialService/GetFinancialReport',
            domunity__pb2.GetFinancialReportRequest.SerializeToString,
            domunity__pb2.FinancialReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaymentHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.FinancialService/GetPaymentHistory',
            domunity__pb2.GetPaymentHistoryRequest.SerializeToString,
            domunity__pb2.PaymentHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventServiceStub(object):
    """==================== Event Service ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEvents = channel.unary_unary(
                '/domunity.EventService/ListEvents',
                request_serializer=domunity__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=domunity__pb2.ListEventsResponse.FromString,
                _registered_method=True)
        self.CreateEvent = channel.unary_unary(
                '/domunity.EventService/CreateEvent',
                request_serializer=domunity__pb2.CreateEventRequest.SerializeToString,
                response_deserializer=domunity__pb2.CreateEventResponse.FromString,
                _registered_method=True)


class EventServiceServicer(object):
    """==================== Event Service ====================
    """

    def ListEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=domunity__pb2.ListEventsRequest.FromString,
                    response_serializer=domunity__pb2.ListEventsResponse.SerializeToString,
            ),
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=domunity__pb2.CreateEventRequest.FromString,
                    response_serializer=domunity__pb2.CreateEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'domunity.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('domunity.EventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventService(object):
    """==================== Event Service ====================
    """

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.EventService/ListEvents',
            domunity__pb2.ListEventsRequest.SerializeToString,
            domunity__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.EventService/CreateEvent',
            domunity__pb2.CreateEventRequest.SerializeToString,
            domunity__pb2.CreateEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ContactServiceStub(object):
    """==================== Contact Service ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendContactForm = channel.unary_unary(
                '/domunity.ContactService/SendContactForm',
                request_serializer=domunity__pb2.ContactFormRequest.SerializeToString,
                response_deserializer=domunity__pb2.ContactFormResponse.FromString,
                _registered_method=True)
        self.RequestOffer = channel.unary_unary(
                '/domunity.ContactService/RequestOffer',
                request_serializer=domunity__pb2.OfferRequest.SerializeToString,
                response_deserializer=domunity__pb2.OfferResponse.FromString,
                _registered_method=True)
        self.RequestPresentation = channel.unary_unary(
                '/domunity.ContactService/RequestPresentation',
                request_serializer=domunity__pb2.PresentationRequest.SerializeToString,
                response_deserializer=domunity__pb2.PresentationResponse.FromString,
                _registered_method=True)


class ContactServiceServicer(object):
    """==================== Contact Service ====================
    """

    def SendContactForm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPresentation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendContactForm': grpc.unary_unary_rpc_method_handler(
                    servicer.SendContactForm,
                    request_deserializer=domunity__pb2.ContactFormRequest.FromString,
                    response_serializer=domunity__pb2.ContactFormResponse.SerializeToString,
            ),
            'RequestOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestOffer,
                    request_deserializer=domunity__pb2.OfferRequest.FromString,
                    response_serializer=domunity__pb2.OfferResponse.SerializeToString,
            ),
            'RequestPresentation': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPresentation,
                    request_deserializer=domunity__pb2.PresentationRequest.FromString,
                    response_serializer=domunity__pb2.PresentationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'domunity.ContactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('domunity.ContactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContactService(object):
    """==================== Contact Service ====================
    """

    @staticmethod
    def SendContactForm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.ContactService/SendContactForm',
            domunity__pb2.ContactFormRequest.SerializeToString,
            domunity__pb2.ContactFormResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.ContactService/RequestOffer',
            domunity__pb2.OfferRequest.SerializeToString,
            domunity__pb2.OfferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPresentation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.ContactService/RequestPresentation',
            domunity__pb2.PresentationRequest.SerializeToString,
            domunity__pb2.PresentationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """==================== Health Check Service ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/domunity.HealthService/Check',
                request_serializer=domunity__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=domunity__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """==================== Health Check Service ====================
    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=domunity__pb2.HealthCheckRequest.FromString,
                    response_serializer=domunity__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'domunity.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('domunity.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """==================== Health Check Service ====================
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/domunity.HealthService/Check',
            domunity__pb2.HealthCheckRequest.SerializeToString,
            domunity__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
