/**
 * @fileoverview gRPC-Web generated client stub for domunity
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.0
// source: domunity.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.domunity = require('./domunity_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.AuthServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.AuthServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.LoginRequest,
 *   !proto.domunity.LoginResponse>}
 */
const methodDescriptor_AuthService_Login = new grpc.web.MethodDescriptor(
  '/domunity.AuthService/Login',
  grpc.web.MethodType.UNARY,
  proto.domunity.LoginRequest,
  proto.domunity.LoginResponse,
  /**
   * @param {!proto.domunity.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.AuthServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.AuthService/Login',
      request,
      metadata || {},
      methodDescriptor_AuthService_Login,
      callback);
};


/**
 * @param {!proto.domunity.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.AuthServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.AuthService/Login',
      request,
      metadata || {},
      methodDescriptor_AuthService_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.RegisterRequest,
 *   !proto.domunity.RegisterResponse>}
 */
const methodDescriptor_AuthService_Register = new grpc.web.MethodDescriptor(
  '/domunity.AuthService/Register',
  grpc.web.MethodType.UNARY,
  proto.domunity.RegisterRequest,
  proto.domunity.RegisterResponse,
  /**
   * @param {!proto.domunity.RegisterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.RegisterResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.RegisterResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.RegisterResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.AuthServiceClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.AuthService/Register',
      request,
      metadata || {},
      methodDescriptor_AuthService_Register,
      callback);
};


/**
 * @param {!proto.domunity.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.RegisterResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.AuthServicePromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.AuthService/Register',
      request,
      metadata || {},
      methodDescriptor_AuthService_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.RefreshTokenRequest,
 *   !proto.domunity.RefreshTokenResponse>}
 */
const methodDescriptor_AuthService_RefreshToken = new grpc.web.MethodDescriptor(
  '/domunity.AuthService/RefreshToken',
  grpc.web.MethodType.UNARY,
  proto.domunity.RefreshTokenRequest,
  proto.domunity.RefreshTokenResponse,
  /**
   * @param {!proto.domunity.RefreshTokenRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.RefreshTokenResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.RefreshTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.RefreshTokenResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.RefreshTokenResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.AuthServiceClient.prototype.refreshToken =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.AuthService/RefreshToken',
      request,
      metadata || {},
      methodDescriptor_AuthService_RefreshToken,
      callback);
};


/**
 * @param {!proto.domunity.RefreshTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.RefreshTokenResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.AuthServicePromiseClient.prototype.refreshToken =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.AuthService/RefreshToken',
      request,
      metadata || {},
      methodDescriptor_AuthService_RefreshToken);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.ForgotPasswordRequest,
 *   !proto.domunity.ForgotPasswordResponse>}
 */
const methodDescriptor_AuthService_ForgotPassword = new grpc.web.MethodDescriptor(
  '/domunity.AuthService/ForgotPassword',
  grpc.web.MethodType.UNARY,
  proto.domunity.ForgotPasswordRequest,
  proto.domunity.ForgotPasswordResponse,
  /**
   * @param {!proto.domunity.ForgotPasswordRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.ForgotPasswordResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.ForgotPasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.ForgotPasswordResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.ForgotPasswordResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.AuthServiceClient.prototype.forgotPassword =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.AuthService/ForgotPassword',
      request,
      metadata || {},
      methodDescriptor_AuthService_ForgotPassword,
      callback);
};


/**
 * @param {!proto.domunity.ForgotPasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.ForgotPasswordResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.AuthServicePromiseClient.prototype.forgotPassword =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.AuthService/ForgotPassword',
      request,
      metadata || {},
      methodDescriptor_AuthService_ForgotPassword);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.UserServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.UserServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.GetProfileRequest,
 *   !proto.domunity.UserProfile>}
 */
const methodDescriptor_UserService_GetProfile = new grpc.web.MethodDescriptor(
  '/domunity.UserService/GetProfile',
  grpc.web.MethodType.UNARY,
  proto.domunity.GetProfileRequest,
  proto.domunity.UserProfile,
  /**
   * @param {!proto.domunity.GetProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.UserProfile.deserializeBinary
);


/**
 * @param {!proto.domunity.GetProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.UserProfile)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.UserProfile>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.UserServiceClient.prototype.getProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.UserService/GetProfile',
      request,
      metadata || {},
      methodDescriptor_UserService_GetProfile,
      callback);
};


/**
 * @param {!proto.domunity.GetProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.UserProfile>}
 *     Promise that resolves to the response
 */
proto.domunity.UserServicePromiseClient.prototype.getProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.UserService/GetProfile',
      request,
      metadata || {},
      methodDescriptor_UserService_GetProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.UpdateProfileRequest,
 *   !proto.domunity.UpdateProfileResponse>}
 */
const methodDescriptor_UserService_UpdateProfile = new grpc.web.MethodDescriptor(
  '/domunity.UserService/UpdateProfile',
  grpc.web.MethodType.UNARY,
  proto.domunity.UpdateProfileRequest,
  proto.domunity.UpdateProfileResponse,
  /**
   * @param {!proto.domunity.UpdateProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.UpdateProfileResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.UpdateProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.UpdateProfileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.UpdateProfileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.UserServiceClient.prototype.updateProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.UserService/UpdateProfile',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateProfile,
      callback);
};


/**
 * @param {!proto.domunity.UpdateProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.UpdateProfileResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.UserServicePromiseClient.prototype.updateProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.UserService/UpdateProfile',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateProfile);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.BuildingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.BuildingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.GetBuildingRequest,
 *   !proto.domunity.Building>}
 */
const methodDescriptor_BuildingService_GetBuilding = new grpc.web.MethodDescriptor(
  '/domunity.BuildingService/GetBuilding',
  grpc.web.MethodType.UNARY,
  proto.domunity.GetBuildingRequest,
  proto.domunity.Building,
  /**
   * @param {!proto.domunity.GetBuildingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.Building.deserializeBinary
);


/**
 * @param {!proto.domunity.GetBuildingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.Building)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.Building>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.BuildingServiceClient.prototype.getBuilding =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.BuildingService/GetBuilding',
      request,
      metadata || {},
      methodDescriptor_BuildingService_GetBuilding,
      callback);
};


/**
 * @param {!proto.domunity.GetBuildingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.Building>}
 *     Promise that resolves to the response
 */
proto.domunity.BuildingServicePromiseClient.prototype.getBuilding =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.BuildingService/GetBuilding',
      request,
      metadata || {},
      methodDescriptor_BuildingService_GetBuilding);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.ListApartmentsRequest,
 *   !proto.domunity.ListApartmentsResponse>}
 */
const methodDescriptor_BuildingService_ListApartments = new grpc.web.MethodDescriptor(
  '/domunity.BuildingService/ListApartments',
  grpc.web.MethodType.UNARY,
  proto.domunity.ListApartmentsRequest,
  proto.domunity.ListApartmentsResponse,
  /**
   * @param {!proto.domunity.ListApartmentsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.ListApartmentsResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.ListApartmentsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.ListApartmentsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.ListApartmentsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.BuildingServiceClient.prototype.listApartments =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.BuildingService/ListApartments',
      request,
      metadata || {},
      methodDescriptor_BuildingService_ListApartments,
      callback);
};


/**
 * @param {!proto.domunity.ListApartmentsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.ListApartmentsResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.BuildingServicePromiseClient.prototype.listApartments =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.BuildingService/ListApartments',
      request,
      metadata || {},
      methodDescriptor_BuildingService_ListApartments);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.FinancialServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.FinancialServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.GetFinancialReportRequest,
 *   !proto.domunity.FinancialReport>}
 */
const methodDescriptor_FinancialService_GetFinancialReport = new grpc.web.MethodDescriptor(
  '/domunity.FinancialService/GetFinancialReport',
  grpc.web.MethodType.UNARY,
  proto.domunity.GetFinancialReportRequest,
  proto.domunity.FinancialReport,
  /**
   * @param {!proto.domunity.GetFinancialReportRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.FinancialReport.deserializeBinary
);


/**
 * @param {!proto.domunity.GetFinancialReportRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.FinancialReport)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.FinancialReport>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.FinancialServiceClient.prototype.getFinancialReport =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.FinancialService/GetFinancialReport',
      request,
      metadata || {},
      methodDescriptor_FinancialService_GetFinancialReport,
      callback);
};


/**
 * @param {!proto.domunity.GetFinancialReportRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.FinancialReport>}
 *     Promise that resolves to the response
 */
proto.domunity.FinancialServicePromiseClient.prototype.getFinancialReport =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.FinancialService/GetFinancialReport',
      request,
      metadata || {},
      methodDescriptor_FinancialService_GetFinancialReport);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.GetPaymentHistoryRequest,
 *   !proto.domunity.PaymentHistory>}
 */
const methodDescriptor_FinancialService_GetPaymentHistory = new grpc.web.MethodDescriptor(
  '/domunity.FinancialService/GetPaymentHistory',
  grpc.web.MethodType.UNARY,
  proto.domunity.GetPaymentHistoryRequest,
  proto.domunity.PaymentHistory,
  /**
   * @param {!proto.domunity.GetPaymentHistoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.PaymentHistory.deserializeBinary
);


/**
 * @param {!proto.domunity.GetPaymentHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.PaymentHistory)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.PaymentHistory>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.FinancialServiceClient.prototype.getPaymentHistory =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.FinancialService/GetPaymentHistory',
      request,
      metadata || {},
      methodDescriptor_FinancialService_GetPaymentHistory,
      callback);
};


/**
 * @param {!proto.domunity.GetPaymentHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.PaymentHistory>}
 *     Promise that resolves to the response
 */
proto.domunity.FinancialServicePromiseClient.prototype.getPaymentHistory =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.FinancialService/GetPaymentHistory',
      request,
      metadata || {},
      methodDescriptor_FinancialService_GetPaymentHistory);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.EventServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.EventServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.ListEventsRequest,
 *   !proto.domunity.ListEventsResponse>}
 */
const methodDescriptor_EventService_ListEvents = new grpc.web.MethodDescriptor(
  '/domunity.EventService/ListEvents',
  grpc.web.MethodType.UNARY,
  proto.domunity.ListEventsRequest,
  proto.domunity.ListEventsResponse,
  /**
   * @param {!proto.domunity.ListEventsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.ListEventsResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.ListEventsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.ListEventsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.ListEventsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.EventServiceClient.prototype.listEvents =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.EventService/ListEvents',
      request,
      metadata || {},
      methodDescriptor_EventService_ListEvents,
      callback);
};


/**
 * @param {!proto.domunity.ListEventsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.ListEventsResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.EventServicePromiseClient.prototype.listEvents =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.EventService/ListEvents',
      request,
      metadata || {},
      methodDescriptor_EventService_ListEvents);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.CreateEventRequest,
 *   !proto.domunity.CreateEventResponse>}
 */
const methodDescriptor_EventService_CreateEvent = new grpc.web.MethodDescriptor(
  '/domunity.EventService/CreateEvent',
  grpc.web.MethodType.UNARY,
  proto.domunity.CreateEventRequest,
  proto.domunity.CreateEventResponse,
  /**
   * @param {!proto.domunity.CreateEventRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.CreateEventResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.CreateEventRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.CreateEventResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.CreateEventResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.EventServiceClient.prototype.createEvent =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.EventService/CreateEvent',
      request,
      metadata || {},
      methodDescriptor_EventService_CreateEvent,
      callback);
};


/**
 * @param {!proto.domunity.CreateEventRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.CreateEventResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.EventServicePromiseClient.prototype.createEvent =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.EventService/CreateEvent',
      request,
      metadata || {},
      methodDescriptor_EventService_CreateEvent);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.ContactServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.ContactServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.ContactFormRequest,
 *   !proto.domunity.ContactFormResponse>}
 */
const methodDescriptor_ContactService_SendContactForm = new grpc.web.MethodDescriptor(
  '/domunity.ContactService/SendContactForm',
  grpc.web.MethodType.UNARY,
  proto.domunity.ContactFormRequest,
  proto.domunity.ContactFormResponse,
  /**
   * @param {!proto.domunity.ContactFormRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.ContactFormResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.ContactFormRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.ContactFormResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.ContactFormResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.ContactServiceClient.prototype.sendContactForm =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.ContactService/SendContactForm',
      request,
      metadata || {},
      methodDescriptor_ContactService_SendContactForm,
      callback);
};


/**
 * @param {!proto.domunity.ContactFormRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.ContactFormResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.ContactServicePromiseClient.prototype.sendContactForm =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.ContactService/SendContactForm',
      request,
      metadata || {},
      methodDescriptor_ContactService_SendContactForm);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.OfferRequest,
 *   !proto.domunity.OfferResponse>}
 */
const methodDescriptor_ContactService_RequestOffer = new grpc.web.MethodDescriptor(
  '/domunity.ContactService/RequestOffer',
  grpc.web.MethodType.UNARY,
  proto.domunity.OfferRequest,
  proto.domunity.OfferResponse,
  /**
   * @param {!proto.domunity.OfferRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.OfferResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.OfferRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.OfferResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.OfferResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.ContactServiceClient.prototype.requestOffer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.ContactService/RequestOffer',
      request,
      metadata || {},
      methodDescriptor_ContactService_RequestOffer,
      callback);
};


/**
 * @param {!proto.domunity.OfferRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.OfferResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.ContactServicePromiseClient.prototype.requestOffer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.ContactService/RequestOffer',
      request,
      metadata || {},
      methodDescriptor_ContactService_RequestOffer);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.PresentationRequest,
 *   !proto.domunity.PresentationResponse>}
 */
const methodDescriptor_ContactService_RequestPresentation = new grpc.web.MethodDescriptor(
  '/domunity.ContactService/RequestPresentation',
  grpc.web.MethodType.UNARY,
  proto.domunity.PresentationRequest,
  proto.domunity.PresentationResponse,
  /**
   * @param {!proto.domunity.PresentationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.PresentationResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.PresentationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.PresentationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.PresentationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.ContactServiceClient.prototype.requestPresentation =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.ContactService/RequestPresentation',
      request,
      metadata || {},
      methodDescriptor_ContactService_RequestPresentation,
      callback);
};


/**
 * @param {!proto.domunity.PresentationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.PresentationResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.ContactServicePromiseClient.prototype.requestPresentation =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.ContactService/RequestPresentation',
      request,
      metadata || {},
      methodDescriptor_ContactService_RequestPresentation);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.HealthServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domunity.HealthServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.domunity.HealthCheckRequest,
 *   !proto.domunity.HealthCheckResponse>}
 */
const methodDescriptor_HealthService_Check = new grpc.web.MethodDescriptor(
  '/domunity.HealthService/Check',
  grpc.web.MethodType.UNARY,
  proto.domunity.HealthCheckRequest,
  proto.domunity.HealthCheckResponse,
  /**
   * @param {!proto.domunity.HealthCheckRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domunity.HealthCheckResponse.deserializeBinary
);


/**
 * @param {!proto.domunity.HealthCheckRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domunity.HealthCheckResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domunity.HealthCheckResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domunity.HealthServiceClient.prototype.check =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domunity.HealthService/Check',
      request,
      metadata || {},
      methodDescriptor_HealthService_Check,
      callback);
};


/**
 * @param {!proto.domunity.HealthCheckRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domunity.HealthCheckResponse>}
 *     Promise that resolves to the response
 */
proto.domunity.HealthServicePromiseClient.prototype.check =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domunity.HealthService/Check',
      request,
      metadata || {},
      methodDescriptor_HealthService_Check);
};


module.exports = proto.domunity;

